# Generated by Django 3.1.5 on 2022-01-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_choices',
            field=models.BooleanField(default=False),
        ),
    ]
