# Generated by Django 3.1.5 on 2022-01-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_has_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_date', models.DateTimeField(verbose_name='invoice date')),
                ('inv_amount', models.IntegerField(default=0)),
                ('receipient', models.CharField(max_length=200)),
                ('inv_desc', models.CharField(max_length=200)),
                ('pmt_date', models.DateTimeField(verbose_name='pmt date')),
                ('street_adr', models.CharField(max_length=200)),
                ('adr_2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
